import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"



const sora = localFont({
  src: [
    { path: '../fonts/sora/Sora-ExtraLight.ttf', weight: '200', style: 'normal' },
    { path: '../fonts/sora/Sora-Light.ttf',        weight: '300', style: 'normal' },
    { path: '../fonts/sora/Sora-Regular.ttf',      weight: '400', style: 'normal' },
    { path: '../fonts/sora/Sora-SemiBold.ttf',     weight: '600', style: 'normal' },
    { path: '../fonts/sora/Sora-Bold.ttf',         weight: '700', style: 'normal' },
    { path: '../fonts/sora/Sora-ExtraBold.ttf',    weight: '800', style: 'normal' },
  ],
  variable: '--font-sora',
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${sora.variable} font-sora antialiased `}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
