import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"



const sora = localFont({
  src: [
    { path: '../fonts/sora/Sora-ExtraLight.ttf', weight: '200', style: 'normal' },
    { path: '../fonts/sora/Sora-Light.ttf',        weight: '300', style: 'normal' },
    { path: '../fonts/sora/Sora-Regular.ttf',      weight: '400', style: 'normal' },
    { path: '../fonts/sora/Sora-SemiBold.ttf',     weight: '600', style: 'normal' },
    { path: '../fonts/sora/Sora-Bold.ttf',         weight: '700', style: 'normal' },
    { path: '../fonts/sora/Sora-ExtraBold.ttf',    weight: '800', style: 'normal' },
  ],
  variable: '--font-sora',
  display: 'swap',
});


const geist = localFont({
  src: [
    { path: '../assets/fonts/geist/Geist-Thin.ttf', weight: '100', style: 'normal' },
    { path: '../assets/fonts/geist/Geist-ExtraLight.ttf', weight: '200', style: 'normal' },
    { path: '../assets/fonts/geist/Geist-Light.ttf', weight: '300', style: 'normal' },
    { path: '../assets/fonts/geist/Geist-Regular.ttf', weight: '400', style: 'normal' },
    { path: '../assets/fonts/geist/Geist-Medium.ttf', weight: '500', style: 'normal' },
    { path: '../assets/fonts/geist/Geist-SemiBold.ttf', weight: '600', style: 'normal' },
    { path: '../assets/fonts/geist/Geist-Bold.ttf', weight: '700', style: 'normal' },
    { path: '../assets/fonts/geist/Geist-ExtraBold.ttf', weight: '800', style: 'normal' },
    { path: '../assets/fonts/geist/Geist-Black.ttf', weight: '900', style: 'normal' },
  ],
  variable: '--font-geist',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Arcade Studios.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${sora.variable} ${geist.variable} font-sora antialiased dark:bg-black bg-zinc-50 `}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
